### ISSUE TITLE
Error in the middle of importing

### ISSUE THREAD

**Issue by NKapanadze** [sviatoslav-lebediev/anki-quizlet-importer-extended#102]
**Describe the bug**
In the middle of the import, the program gives an error. It never reaches the last card. This happens on (almost) all decks.

**Quizlet deck URL**
https://quizlet.com/ru/813299987/0607-flash-cards/

**Additional context**
Error from the addon window: 
Ошибка
Отладочная информация:
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-05 18:42:52

Caught exception:
Traceback (most recent call last):
  File "C:\Users\nikol\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\nikol\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 432, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\nikol\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 480, in fileDownloader
    raise e
  File "C:\Users\nikol\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by NKapanadze** [comment]
And usually it is the same card that triggers the error over and over again.

**Comment by sviatoslav-lebediev** [comment]
Hi, sorry, I haven't seen your message. Try to check a `skip errors` checkbox. It will skip "bad" audio or image URLs

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, if you still can't import the deck please create a new issue
