### ISSUE TITLE
Error bug on quizlet add on 

### ISSUE THREAD

**Issue by ttran9898** [sviatoslav-lebediev/anki-quizlet-importer-extended#106]
**Describe the bug**
Error on quizlet add on. I tried using the short and full URL as described but it still does not work. 

**Quizlet deck URL**
https://quizlet.com/814663779/lab-5-part-2-infratemporal-fossa-flash-cards/?funnelUUID=e7206a9e-f2d1-4c9d-8b4f-b3d7dd90df85

**Additional context**
Error from the addon window

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-11.7.8-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-19 12:45:32
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/tt/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/tt/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/tt/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/Users/tt/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please try to check a `Skip error` checkbox ?

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/949d3fb0-ae89-426e-96e9-0fcd7cc0d665)
