### ISSUE TITLE
importing error

### ISSUE THREAD

**Issue by mououu** [sviatoslav-lebediev/anki-quizlet-importer-extended#108]
**Describe the bug**
only gets to importing 27/45 cards, then displays error message :(

**Quizlet deck URL**
https://quizlet.com/653860637/s2u2-palabras-interrogativas-en-espanol-flash-cards/

**Additional context**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-20 02:45:39

Caught exception:
Traceback (most recent call last):
  File "C:\Users\16124\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\16124\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 426, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\16124\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 480, in fileDownloader
    raise e
  File "C:\Users\16124\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by sviatoslav-lebediev** [comment]
hi, try this https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/106#issuecomment-1643363466
