### ISSUE TITLE
fails during import

### ISSUE THREAD

**Issue by nextDC** [sviatoslav-lebediev/anki-quizlet-importer-extended#110]
Partial import. Import fails at 8/67 flashcards.
Have tried URL, HTML & Incognito methods. 
Tried without audio, tried with skip errors.
Have tried logged into Quizlet with "qlts" set.

https://quizlet.com/146597052/section-21-general-concepts-ch-36-40-flash-cards/

Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-07-27 14:05:57
Add-ons possibly involved: ⁨Improved Quizlet to Anki 21 Importer⁩

Caught exception:
Traceback (most recent call last):
  File "urllib.request", line 1346, in do_open
  File "http.client", line 1285, in request
  File "http.client", line 1331, in _send_request
  File "http.client", line 1280, in endheaders
  File "http.client", line 1040, in _send_output
  File "http.client", line 980, in send
  File "http.client", line 1454, in connect
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1041, in _create
  File "ssl", line 1310, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/me/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/me/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 517, in open
  File "urllib.request", line 534, in _open
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 1389, in https_open
  File "urllib.request", line 1349, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>

**Comment by sviatoslav-lebediev** [comment]
Hi try this https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/106#issuecomment-1643363466

**Comment by nextDC** [comment]
Thank you for your reply. 

1. Have tried URL, HTML & Incognito methods.
2. Tried without audio, tried with skip errors.
3. Have tried logged into Quizlet with "qlts" set.

**Comment by sviatoslav-lebediev** [comment]
And it didn't help ?
This error CERTIFICATE_VERIFY_FAILED means that this site `https` has an invalid certificate, but it looks like all images are from quizlet.com.  

I've tried to import your deck and didn't see any issues

[Section 2.1 - General Concepts (Ch 36 - 40).apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/12207726/Section.2.1.-.General.Concepts.Ch.36.-.40.apkg.zip)

**Comment by nextDC** [comment]
I'm sorry it was the Incoggo blocker I had installed that was the issue. Apologies.
