### ISSUE TITLE
Don't understand the problem with import

### ISSUE THREAD

**Issue by Pasasaske** [sviatoslav-lebediev/anki-quizlet-importer-extended#111]
So, not so much understand what the problem is, but if exist a solving, it will be pleasure.

Ошибка
Произошла ошибка. Запустите Anki, зажав Shift, чтобы временно отключить дополнения.
Если проблема появляется со включёнными дополнениями, выберите в меню «Инструменты» — «Дополнения», чтобы отключить разные дополнений, и перезапустите Anki. Повторяйте эти действия, пока не найдёте проблемное дополнение.
Когда вы найдёте дополнение, вызвавшее ошибки, пожалуйста, сообщите об них на дополнения на сайте поддержки.
Отладочная информация:
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-12.4-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-30 10:21:01
Причиной могли послужить: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "urllib.request", line 1346, in do_open
  File "http.client", line 1285, in request
  File "http.client", line 1331, in _send_request
  File "http.client", line 1280, in endheaders
  File "http.client", line 1040, in _send_output
  File "http.client", line 980, in send
  File "http.client", line 1447, in connect
  File "http.client", line 946, in connect
  File "socket", line 823, in create_connection
  File "socket", line 954, in getaddrinfo
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slogger/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/slogger/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 426, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/slogger/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 517, in open
  File "urllib.request", line 534, in _open
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 1389, in https_open
  File "urllib.request", line 1349, in do_open
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

**Comment by sviatoslav-lebediev** [comment]
Hi, it would be great to look at the deck you are trying to import. 
At first glance, the add-on can't download some audio URLs. I would try to check the `Skip errors` checkbox and import one more time.
