### ISSUE TITLE
Cannot import whole deck. Stuck at 7th entry. Tried html method as well

### ISSUE THREAD

**Issue by TheOmnivert** [sviatoslav-lebediev/anki-quizlet-importer-extended#114]
**Describe the bug**
Only 7 cards get imported then it shows the below error. Tried the html method, that didn't work as well.

**Quizlet deck URL**
https://quizlet.com/in/501825718/set-3-flash-cards/
**Additional context**

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-08-26 14:32:41

Caught exception:
Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\[redacted]\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "C:\Users\[redacted]\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 480, in fileDownloader
    raise e
  File "C:\Users\[redacted]\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/115#issuecomment-1694746595

**Comment by TheOmnivert** [comment]
Thanks it worked.
