### ISSUE TITLE
Cannot import past 101 flashcards, mainly with images

### ISSUE THREAD

**Issue by 1010oreos** [sviatoslav-lebediev/anki-quizlet-importer-extended#115]
**Describe the bug**
Cannot import past 101 flashcards from quizlet, I also tried the HTML and it also stopped at 101 cards. Both decks had plenty of images, decks without images seem to upload fine.

**Quizlet deck URL**
https://quizlet.com/612914589/week-1-introreview-of-the-skull-cn-facial-bones-cranial-bones-vertebrae-flash-cards/?funnelUUID=3e961724-b3ef-4b8a-b013-612aa66b39e5

**Additional context**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4.1-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-08-25 18:53:37
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/redacted/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/redacted/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/redacted/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/Users/redacted/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, please try to check the `Skip errors` checkbox, It looks like, Quizlet returns 403 for some of your images

![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/e5761cf6-2482-4a0d-9169-5cce69a3f87f)
