### ISSUE TITLE
Error when importing deck due to image downloading?

### ISSUE THREAD

**Issue by jjm4000** [sviatoslav-lebediev/anki-quizlet-importer-extended#117]
**Describe the bug**
Got this error when trying to import deck, seems to be related to images.

**Quizlet deck URL**
https://quizlet.com/613251883/flashcards

**Additional context**

Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-09-11 22:47:46
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/name/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/name/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/name/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/Users/name/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 410: Gone

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please take a look at this comment ? https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/115#issuecomment-1694746595

**Comment by jjm4000** [comment]
That worked, thank you!
