### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AhmadMoussaOCSB** [sviatoslav-lebediev/anki-quizlet-importer-extended#123]
Hi, I'm trying to import decks but I always face this error, I tried solutions like reinstalling the add-on, and renaming the note type but still no luck.
This is the error message:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-08 16:28:31

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Ahmad\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\Ahmad\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "C:\Users\Ahmad\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 480, in fileDownloader
    raise e
  File "C:\Users\Ahmad\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, this `file_name = self.fileDownloader(item["imageUrl"])` means that for some reason the add-on can't fetch an image.
Try to check `Skip errors` and it will skip images that it can't import
