### ISSUE TITLE
Imports with Audio fail frequently, repeated imports create duplicates.

### ISSUE THREAD

**Issue by lucmartialadam** [sviatoslav-lebediev/anki-quizlet-importer-extended#126]
**Describe the bug**
Whenever I try to import a deck with "download audio" checked, it fails repeatedly. It seems to be able to import a few before breaking. If I uncheck download audio, it imports perfectly. The decks themselves work perfectly fine on quizlet with audio. 

**Quizlet deck URL**
I've tried this with multiple decks with audio with the same result. 

https://quizlet.com/312676214/bi-hfw-1-5-unit-2-vocabulary-flash-cards/

**Additional context**
Error from the addon window

"Caught exception:
Traceback (most recent call last):
  File "/Users/lucienadam/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/lucienadam/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 426, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/lucienadam/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/Users/lucienadam/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 504: Gateway Timeout"

I've gotten 502 and 400 as well.

**Comment by sviatoslav-lebediev** [comment]
Hi, I would try to check your network connection and if you still have this issue - try to check `Skip errors`, it will skip a few audios that it can't download for some reason.
