### ISSUE TITLE
The add-on stopped importing quizlet decks

### ISSUE THREAD

**Issue by Megan22a** [sviatoslav-lebediev/anki-quizlet-importer-extended#127]
**Describe the bug**
A description of what the bug is.

**[Quizlet deck URL](https://quizlet.com/841345373/introduction-to-innate-and-adaptive-immune-responses-flash-cards/?i=58g812&x=1jqt)**

**Additional context**
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4.1-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-10-22 19:21:35
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/armaghan/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/armaghan/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 426, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/armaghan/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/Users/armaghan/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

**Comment by sviatoslav-lebediev** [comment]
Hi, I would try to check your network connection and if you still have this issue - try to check `Skip errors`, it will skip a few audios that it can't download for some reason.
