### ISSUE TITLE
Error while importing from Quizlet

### ISSUE THREAD

**Issue by ShackerFox** [sviatoslav-lebediev/anki-quizlet-importer-extended#129]
**Describe the bug**
_A description of what the bug is._
The program works normal at start but after importing 53 cards, it displays an error.
**Quizlet deck URL**
https://quizlet.com/in/845089728/economics-the-allocation-of-resources-flash-cards/?funnelUUID=84034ba5-a516-43c6-bde5-a2f70efadff5
**Additional context**
Tried importing from the HTML version, but had no success.
t**Error from the addon windowt**
```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-28 16:30:06
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 480, in fileDownloader
    raise e
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by sviatoslav-lebediev** [comment]
pls take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/115#issuecomment-1694746595
