### ISSUE TITLE
Quizlet set will not import if download audio is selected

### ISSUE THREAD

**Issue by teavsie** [sviatoslav-lebediev/anki-quizlet-importer-extended#133]
When importing a quizlet set with download audio selected (with just long link or long link and html) an error will occur. If you deselect the "download" audio checklist, it will upload properly (without any audio, of course).

[**Quizlet deck URL**](https://quizlet.com/847607465/apprenons-chapitre-4-vocabulaire-flash-cards/)

**Error description:**
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-11-06 09:40:02
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/altheaivins/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 379, in onCode
    self.createDeck(deck)
  File "/Users/altheaivins/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 432, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/altheaivins/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 486, in fileDownloader
    raise e
  File "/Users/altheaivins/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 477, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, try to check - `Skip errors`. Sometimes it can't download 1 or 2 audio urls.

**Comment by teavsie** [comment]
Hi! I don't see an option to skip errors anywhere. I am give the option to copy the error to clipboard or close error window.

**Comment by sviatoslav-lebediev** [comment]
I meant this 
![image](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/assets/19693768/5a5b180b-5423-458a-99a0-c012a54fe5f0)
