### ISSUE TITLE
my quizlet is not imported!

### ISSUE THREAD

**Issue by OGN97** [sviatoslav-lebediev/anki-quizlet-importer-extended#136]
**Describe the bug**
A description of what the bug is. i used the add one and it works except for this link

**Quizlet deck URL** https://quizlet.com/828129585/flashcards?funnelUUID=28140eba-896d-4985-a6a1-4e602617539e

**Additional context**
Error from the addon window

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.2.1-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-11-14 22:25:35
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/omartotonji/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    showText(self.thread.errorMessage)
  File "/Users/omartotonji/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 426, in createDeck
    note["FrontText"] = item["term"]
  File "/Users/omartotonji/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    f.write(r.read())
  File "/Users/omartotonji/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    def fileDownloader(self, url, suffix=''):
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by OGN97** [comment]
Hello

Thanks for the reply

Yea this fix the problem


Thanks a lot

sviatoslav-lebediev ***@***.***> schrieb am Do. 16. Nov. 2023
um 1:35 PM:
