### ISSUE TITLE
Error when attempting to import - no other add-ons

### ISSUE THREAD

**Issue by magicvovo** [sviatoslav-lebediev/anki-quizlet-importer-extended#138]
**Describe the bug**
Attempting to import a quizlet deck, I receive an error stating it's caused by another add-on. Except, I have no other quizlet add-ons, only this one. I've tried multiple quizlet decks, but continue to get the error. Error info pasted into the additional context field.

**Quizlet deck URL**
https://quizlet.com/682029414/aws-sysops-flash-cards/

**Additional context**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-18 19:20:39
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\mattb\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 379, in onCode
    self.createDeck(deck)
  File "C:\Users\mattb\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\mattb\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    raise e
  File "C:\Users\mattb\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 477, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
this `file_name = self.fileDownloader(self.getAudioUrl(` + this  `urllib.error.HTTPError: HTTP Error 403: Forbidden`
means that you can't download audio. If you don't need audio uncheck the `Download audio` checkbox or check `Skip errors` one
