### ISSUE TITLE
Error when attempting to import

### ISSUE THREAD

**Issue by ToffeeUni** [sviatoslav-lebediev/anki-quizlet-importer-extended#141]
**Describe the bug**
A description of what the bug is.
Attempting to import a quizlet deck, I receive an error. 've tried multiple quizlet decks, but continue to get the error. Error info pasted into the additional context field.
**Quizlet deck URL**
https://quizlet.com/vn/668319819/thuc-hanh-giai-phau-benh-flash-cards/

**Additional context**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.1.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-08 18:53:28
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/richellelenguyen/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 379, in onCode
    self.createDeck(deck)
  File "/Users/richellelenguyen/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/richellelenguyen/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 486, in fileDownloader
    raise e
  File "/Users/richellelenguyen/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 477, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, some decks cloudflare protects for some reason, I haven't found a good way to fix this. So for now, you can uncheck `Download audio` or check `Skip errors`.

**Comment by sviatoslav-lebediev** [comment]
p.s. here is your deck 
[THỰC HÀNH GIẢI PHẪU BỆNH.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/13628195/TH.C.HANH.GI.I.PH.U.B.NH.apkg.zip)

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, please join this discussion https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156
