### ISSUE TITLE
Quizlet importer doesn't find the according URL for the deck

### ISSUE THREAD

**Issue by SleepingPig35** [sviatoslav-lebediev/anki-quizlet-importer-extended#144]
**Describe the bug**
Quizlet importer doesn't find the according URL for the deck. Perhaps, the URL for parsing the Quizlet deck has changed?

**Quizlet deck URL**
https://quizlet.com/48203639/a-level-and-gcse-ambitious-vocabulary-flash-cards
**Additional context**
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the [add-ons section](https://forums.ankiweb.net/c/add-ons/11) of our support site. 
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-11 18:34:52
Add-ons possibly involved: ⁨Improved Quizlet to Anki 21 Importer⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 426, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 480, in fileDownloader
    raise e
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, I guess that's the same 'audio' issue https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/141#issuecomment-1848987813
