### ISSUE TITLE
Error when i try to download some decks

### ISSUE THREAD

**Issue by jemesol** [sviatoslav-lebediev/anki-quizlet-importer-extended#145]
Hi, i have been trying to download some decks from quizlets, anyone for me works... every single time give me this error: 

Información de depuración:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22000
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-12 21:32:39
Complementos posiblemente implicados: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 379, in onCode
    self.createDeck(deck)
  File "C:\Users\LENOVO\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 426, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

**Quizlet deck URL**

https://quizlet.com/es/571032566/netzwerk-neu-b1-kapitel-1-gute-reise-flash-cards/?funnelUUID=159f93f2-ba37-47ed-951d-63a084ed9efb

I have already try with the HTML paste but doesn´t work.

**Comment by sviatoslav-lebediev** [comment]
Hi, could you take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/103#issuecomment-1629578103 ?
