### ISSUE TITLE
Error in importing a deck

### ISSUE THREAD

**Issue by jocyfajardo** [sviatoslav-lebediev/anki-quizlet-importer-extended#148]
**Describe the bug**
A description of what the bug is.

**Quizlet deck URL**. https://quizlet.com/653578552/pn-idl-mt-101-chapter-12-and-chapter-13-flash-cards/

**Additional context**
Error from the addon window

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-12.4-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-22 23:07:39
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/jocelynamberfajardo/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/jocelynamberfajardo/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 426, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/jocelynamberfajardo/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/Users/jocelynamberfajardo/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at this comment https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/141#issuecomment-1848987813

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, please join this discussion https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156
