### ISSUE TITLE
Import of deck produces errors

### ISSUE THREAD

**Issue by Gardenflex** [sviatoslav-lebediev/anki-quizlet-importer-extended#159]
**Describe the bug**
Hello,
first of all - thanks for your fantastic work!
When I want to import the deck, it produces the error "Anki encountered a problem. Please follow the troubleshooting steps."
I followed the troubleshooting guide, but nothing changed.

**Quizlet deck URL**
https://quizlet.com/de/866690593/japanisch-bitte-l9-l12-flash-cards/

**Additional context**
"Anki encountered a problem. Please follow the troubleshooting steps."

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.5.0-kali3-amd64-x86_64-with-glibc2.37

Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/home/user/.local/share/Anki2/addons21/1362209126/__init__.py", line 426, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/home/user/.local/share/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/home/user/.local/share/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2023-12-17T13:35, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, I guess this is the same issue https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/158

**Comment by sviatoslav-lebediev** [comment]
going to close, 99% this is related to the audio issue, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156
