### ISSUE TITLE
Cannot import from Quizlet to Anki with new update

### ISSUE THREAD

**Issue by mbryant1832** [sviatoslav-lebediev/anki-quizlet-importer-extended#161]
**Describe the bug**
With new update, Anki is prompting "Anki encountered a problem" error, indicating Add-Ons possibly involved, pointing to Quizlet to Anki 21 Importer with audio support. This is happening even with the 'Skip Errors' checked.

**Quizlet deck URL**
https://quizlet.com/761507951/korean-level-1-vocab-flash-cards/

**Additional context**
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "C:\Users\JadeR\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "C:\Users\JadeR\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JadeR\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\JadeR\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\JadeR\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 488, in fileDownloader
    if fallback and not fallback_call and self.config['license']:
KeyError: 'license'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-14T11:12, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
hi, my bad, will be fixed soon

**Comment by sviatoslav-lebediev** [comment]
should be fixed

**Comment by mbryant1832** [comment]
working now!

**Comment by sviatoslav-lebediev** [comment]
cool, if you have issues with audio take a look at this discussion https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156
you can send an email to me at moro.programmer@gmail.com and I will give you a key
