### ISSUE TITLE
'throwing exception 403' when trying to import Quizlet deck

### ISSUE THREAD

**Issue by aaearon** [sviatoslav-lebediev/anki-quizlet-importer-extended#162]
**Describe the bug**
When trying to import deck https://quizlet.com/nl/218836453/hoofdstuk-1-nederlands-in-gang-nederlands-engels-flash-cards/?setIdOrUsername=218836453, exception 403 is thrown. Skipping errors does not help.

The deck is created but is empty.

Seemingly related to #156 ?

**Quizlet deck URL**
https://quizlet.com/nl/218836453/hoofdstuk-1-nederlands-in-gang-nederlands-engels-flash-cards/?setIdOrUsername=218836453

**Additional context**
```Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\Tim.Schindler\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\Tim.Schindler\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\Tim.Schindler\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 497, in fileDownloader
    raise e
  File "C:\Users\Tim.Schindler\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "C:\Users\Tim.Schindler\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T19:55, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

```

**Comment by sviatoslav-lebediev** [comment]
yes it's 100% related to the audio issue, but I don't understand why `Skipping errors does not help.`
If you don't need audio - try to uncheck `Download audio`. If you need audio - email me at moro.programmer@gmail.com and i will send you a beta tester key
p.s. here is your deck 
[Hoofdstuk 1 Nederlands in gang Nederlands-Engels.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/13954736/Hoofdstuk.1.Nederlands.in.gang.Nederlands-Engels.apkg.zip)

**Comment by sviatoslav-lebediev** [comment]
more info
https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/discussions/156
https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
