### ISSUE TITLE
Completed - my apologies

### ISSUE THREAD

**Issue by suadabdi** [sviatoslav-lebediev/anki-quizlet-importer-extended#175]
Unable to import flashcards to anki. Keep receiving the same error despite checking with multiple flashcards and reinstalling anki, checking updates and installing and uninstalling the addon.

Quizlet deck URL: https://quizlet.com/gb/891397417/muscle-proteins-degradation-and-n-metabolism-flash-cards/?new

Error from the addon window is:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\admin\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 431, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Table ['1237621971', 2023-06-18T12:37, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T08:15, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T18:55, 'None', '']
ReColor ['688199788', 2024-03-03T01:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1237621971 1362209126 1374772155 1771074083 688199788

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by suadabdi** [comment]
Sorry, I managed to check over the debug info and deleted the note type Basic Quizlet Extended and it worked. Thank you. If you could close this issue that would be great. Thank you so much.
