### ISSUE TITLE
Quizlet to anki add on does not work

### ISSUE THREAD

**Issue by sunshine7657654** [sviatoslav-lebediev/anki-quizlet-importer-extended#176]
**Describe the bug**
A description of what the bug is.
When I try to import my quizlet deck it says exception - 403. 

**Quizlet deck URL**
https://quizlet.com/gb/890306475/hand-and-wrist-anatomy-flash-cards/?funnelUUID=0448aa53-0724-46c3-a21f-2d78c682f24e

**Additional context**
Error from the addon window
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "C:\Users\4vane\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\4vane\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\4vane\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 497, in fileDownloader
    raise e
  File "C:\Users\4vane\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "C:\Users\4vane\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Image Occlusion Enhanced ['1374772155', 2022-04-09T08:15, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T18:55, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
Spell Checker ['369581638', 2023-10-11T14:47, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1374772155 1771074083 369581638

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ (1st item)

**Comment by sviatoslav-lebediev** [comment]
if you need audio - send an email to me and I will send you a key. https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/How-to-use-a-license-key
