### ISSUE TITLE
Issues Converting quizlets

### ISSUE THREAD

**Issue by Reeceblank** [sviatoslav-lebediev/anki-quizlet-importer-extended#180]
In any attempt to try and convert quizlet decks to anki's, I paste the long version of the URL into the add on, unselect audio, and then let it do its thing. This has worked for me for a long time now, until just yesterday I would get to some variation of 6/65 cards or 9/65 cards or 7/57 cards done, the add on would stop there and I would get a problem popup. 

Quizlet URL: https://quizlet.com/688515713/medicine-orthopedics-shoulder-elbow-flash-cards/?funnelUUID=8c90ed63-573d-425f-adf3-9a12d2834edb

When I copied the debug info: (sorry for how long this is)
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "urllib3.connection", line 203, in _new_conn
  File "urllib3.util.connection", line 60, in create_connection
  File "socket", line 954, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3.connectionpool", line 790, in urlopen
  File "urllib3.connectionpool", line 491, in _make_request
  File "urllib3.connectionpool", line 467, in _make_request
  File "urllib3.connectionpool", line 1096, in _validate_conn
  File "urllib3.connection", line 611, in connect
  File "urllib3.connection", line 210, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002829285E6D0>: Failed to resolve 'quizlet.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests.adapters", line 486, in send
  File "urllib3.connectionpool", line 844, in urlopen
  File "urllib3.util.retry", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='quizlet.com', port=443): Max retries exceeded with url: /webapi/3.9/sets/688515713 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002829285E6D0>: Failed to resolve 'quizlet.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\blank\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 591, in getDataFromApi
    deckResponse = requests.get(deckUrl, verify=False, headers=headers)
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='quizlet.com', port=443): Max retries exceeded with url: /webapi/3.9/sets/688515713 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002829285E6D0>: Failed to resolve 'quizlet.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\blank\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 746, in run
    self.getDataFromApi()
  File "C:\Users\blank\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 608, in getDataFromApi
    e, itemsResponse.text)
UnboundLocalError: local variable 'itemsResponse' referenced before assignment

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T13:55, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1374772155

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

Not sure what is going on, but I have restarted my anki, removed and reloaded the add-on, but no such luck

**Comment by sviatoslav-lebediev** [comment]
Hi, hm, this is a strange error. What it says is that it can't find a Quizlet domain. `Failed to resolve 'quizlet.com' ([Errno 11001] getaddrinfo failed)"))`. So it looks like it's some network issue on your side. Maybe there is some issue with the DNS. Have you tried to open that link in your browser? 
p.s I've tried to import your deck and everything looks ok. You can take it here

[Medicine (Orthopedics)_ Shoulder & Elbow.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/14971835/Medicine.Orthopedics._.Shoulder.Elbow.apkg.zip)

**Comment by Reeceblank** [comment]
Yeah, super strange without a doubt. Funny enough after seeing your message, I attempted to use the add-on on a different wireless network and it worked fine! Sorry to take up your time, and you can close the issue! I really appreciate the help!

**Comment by sviatoslav-lebediev** [comment]
Cool, thank you for letting me known
