### ISSUE TITLE
Quizlet Importer

### ISSUE THREAD

**Issue by havyngl** [sviatoslav-lebediev/anki-quizlet-importer-extended#183]
**Describe the bug**
A description of what the bug is.
I followed the steps as directed but there's only a deck without any cards
**Quizlet deck URL**
https://quizlet.com/vn/837959413/speaking-flash-cards/
**Additional context**

This is the debug info, please help me

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.18363

Traceback (most recent call last):
  File "urllib.request", line 1346, in do_open
  File "http.client", line 1285, in request
  File "http.client", line 1331, in _send_request
  File "http.client", line 1280, in endheaders
  File "http.client", line 1040, in _send_output
  File "http.client", line 980, in send
  File "http.client", line 1454, in connect
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1074, in _create
  File "ssl", line 1343, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LeThiThuHien\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\LeThiThuHien\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\LeThiThuHien\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "C:\Users\LeThiThuHien\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 517, in open
  File "urllib.request", line 534, in _open
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 1389, in https_open
  File "urllib.request", line 1349, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add-on folder with readable names ['519936472', 2020-03-07T10:36, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T17:10, 'None', '']
AnkiConnect ['2055492159', 2024-02-27T11:37, 'None', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-04-15T21:06, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-16T01:55, 'None', '']
Sentence adder for any language with batch add option ['1682655437', 2024-02-15T13:21, 'None', '']
maobi - Chinese Hanzi Writing Quizzes in Anki v0 5 2 ['931477147', 2021-02-22T00:14, 'None', mod]

===IDs of active AnkiWeb add-ons===
1362209126 1436550454 1682655437 2055492159 519936472 744725736 931477147

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, hm it's a strange error, it can't verify SSL. I don't think it's related to the add-on. I would try with another network/laptop if it's possible
Here is your deck 
[Speaking.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/15431415/Speaking.apkg.zip)

**Comment by havyngl** [comment]
Thank you so much
