### ISSUE TITLE
Fail upon install? MacOS-12.7.5 Intel

### ISSUE THREAD

**Issue by DrHooBs** [sviatoslav-lebediev/anki-quizlet-importer-extended#188]
Anki 24.06.2 (33a92379)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-12.7.5-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/harry/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 728, in runQuizletPlugin
    __window = QuizletWindow()
  File "/Users/harry/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 136, in __init__
    self.initGUI()
  File "/Users/harry/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 182, in initGUI
    self.text_url.setFocusPolicy(Qt.StrongFocus)
AttributeError: type object 'Qt' has no attribute 'StrongFocus'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Improved Quizlet to Anki 21 Importer ['1362209126', 0, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

Steps to reproduce:
Have no other addons installed/active
Install addon
restart anki
press import deck from quizlet

**Comment by sviatoslav-lebediev** [comment]
hm, it's interesting, because on my mac it works
```
Version ⁨24.06.2 (33a92379)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
```
but I have m1.

Could you please try to open this file `/Users/harry/Library/Application Support/Anki2/addons21/1362209126/init.py` and remove that line `self.text_url.setFocusPolicy(Qt.StrongFocus)` + restart anki

**Comment by DrHooBs** [comment]
Must be an intel mac issue? I found the release on the Anki site to be working though so must be an issue with the github release.
Anki 24.06.2 (33a92379)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-12.7.5-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/harry/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 727, in runQuizletPlugin
    __window = QuizletWindow()
  File "/Users/harry/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 136, in __init__
    self.initGUI()
  File "/Users/harry/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 275, in initGUI
    self.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
AttributeError: type object 'QSizePolicy' has no attribute 'Minimum'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Improved Quizlet to Anki 21 Importer ['1362209126', 0, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
oh, interesting, maybe i need to add a new version to github
