### ISSUE TITLE
Error in "improved Quizlet to Anki Importer"

### ISSUE THREAD

**Issue by kelseylynnyeh** [sviatoslav-lebediev/anki-quizlet-importer-extended#194]
**Describe the bug**
Won't let me download quizlet deck into anki 

**Quizlet deck URL**
https://quizlet.com/841115003/italki-lessons-flash-cards/?i=37n7j5&x=1jqt

**Additional context**
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.3-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/kelseyyeh/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/kelseyyeh/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "/Users/kelseyyeh/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 497, in fileDownloader
    raise e
  File "/Users/kelseyyeh/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/kelseyyeh/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T10:55, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
1st item

**Comment by sviatoslav-lebediev** [comment]
going to close, reopen it if you still have this issue
