### ISSUE TITLE
Error please help 

### ISSUE THREAD

**Issue by xxlBrain** [sviatoslav-lebediev/anki-quizlet-importer-extended#198]
**Describe the bug**
A description of what the bug is.¨
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\loris\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\loris\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\loris\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 497, in fileDownloader
    raise e
  File "C:\Users\loris\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "C:\Users\loris\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T19:55, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Quizlet deck URL**
https://quizlet.com/ch/152855185/cours-intensif-2-lecon-1-flash-cards/?i=2x03l6&x=1jqY

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, please read this https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
1st item

**Comment by sviatoslav-lebediev** [comment]
p.s here is your deck
[Cours intensif 2 - Leçon 1.apkg.zip](https://github.com/user-attachments/files/16975780/Cours.intensif.2.-.Lecon.1.apkg.zip)

**Comment by xxlBrain** [comment]
Thank you very much.
