### ISSUE TITLE
403 Error Thrown when importing deck

### ISSUE THREAD

**Issue by CarolinePirtle** [sviatoslav-lebediev/anki-quizlet-importer-extended#202]
**Describe the bug**
When importing a flashcard set from Quizlet, I would get a 403 error. This seemed to be fixed by having ANYTHING in the start phrase field. I tried being signed in, public deck, and my own deck, and this bug was consistent. 

**Quizlet deck URL**
https://quizlet.com/824942035/bio-exam-1-ave-josefowski-flash-cards/?funnelUUID=9db1fd74-065b-4a50-afe8-cd39c7294aa6
**Additional context**
Error from the addon window
NOTE: I did NOT create this deck, any names present are not me/ have been removed

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2024-09-17 11:30:04

Caught exception:
Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "C:\Users\name\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 437, in createDeck
    file_name = self.fileDownloader(self.getAudioUrl(
  File "C:\Users\name\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 497, in fileDownloader
    raise e
  File "C:\Users\name\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "C:\Users\name\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
1st item

**Comment by sviatoslav-lebediev** [comment]
I've released a new version, please try to update and import one more time. I'm going to close this issue. If you still have this error please create a new one
