### ISSUE TITLE
403 Error code thrown when importing a quizlet with pictures

### ISSUE THREAD

**Issue by aoberhofer705** [sviatoslav-lebediev/anki-quizlet-importer-extended#204]
Quizlet just did an update the other day, and since then when I import a Quizlet deck with pictures the deck can convert but without the pictures. it throws a 403 error for every picture it encounters. I tried with multiple decks with pictures and none of them worked. The quizlet linked was the first one I tried. Thank you.

[**Quizlet deck URL**](https://quizlet.com/951895286/htn-flash-cards/?funnelUUID=2a958e3b-0abc-4225-896e-a7d16c288188)

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/abbyoberhofer/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/abbyoberhofer/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 449, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/abbyoberhofer/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 497, in fileDownloader
    raise e
  File "/Users/abbyoberhofer/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/abbyoberhofer/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
OpenInExternalEditorRenameDuplicate for ImageAudioVideo WinLinux ['1560623518', 2023-03-19T13:33, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T13:55, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1560623518

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, I will take a look

**Comment by sviatoslav-lebediev** [comment]
@Chesnie601 i will release a fixed version soon

**Comment by sviatoslav-lebediev** [comment]
going to close this issue, if you still see 403 create a new one
