### ISSUE TITLE
cannot import images from quizlet and throws error can only import text when press skip error 

### ISSUE THREAD

**Issue by grace288** [sviatoslav-lebediev/anki-quizlet-importer-extended#205]
**Describe the bug**
A description of what the bug is.
cannot import from quizlet and throws error
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/ming/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/ming/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 449, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/ming/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 497, in fileDownloader
    raise e
  File "/Users/ming/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/ming/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Create Filtered Deck from the Browser ['861263371', 2017-08-29T14:57, 'None', '']
Enhance main window ['877182321', 2023-10-22T16:28, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T13:55, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1374772155 1771074083 861263371 877182321

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Quizlet deck URL**
https://quizlet.com/938777557/mri-pathology-intro-to-general-pathologies-flash-cards/

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, thanks for the detailed description. We already have this issue https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/204. I'm going to close this one in favor of the older issue

p.s. for now you can use this add-on https://ankiweb.net/shared/info/874215009 and add images manually. Just copy an image from the deck and paste it to the image field
![image](https://github.com/user-attachments/assets/dfbf6b74-5d6f-4a84-90d8-690bf308a03d)

**Comment by grace288** [comment]
Hi thank you for letting me know but i really liked how the add on included images transfer as well. Please let me know when it will be available again. Thanks alot !

**Comment by sviatoslav-lebediev** [comment]
Hi, I've fixed the issue, going to release a fix soon
p.s here is your deck

[Mri Pathology Intro to general pathologies.apkg.zip](https://github.com/user-attachments/files/17305779/Mri.Pathology.Intro.to.general.pathologies.apkg.zip)

**Comment by grace288** [comment]
Thank you so much for the fix. Have a great weekend !
