### ISSUE TITLE
403 Error Code 

### ISSUE THREAD

**Issue by tinhile4** [sviatoslav-lebediev/anki-quizlet-importer-extended#206]
Tried to import multiple Quizlet decks with pictures; the deck can only convert but without the pictures. it throws a 403 error for every picture it encounters. I tried with multiple decks with pictures and none of them worked. I liked the quizlet sets that I've tried. Thank you. 

https://quizlet.com/741093732/exam-2-radiograph-images-flash-cards/?i=1iyt49&x=1jqt
https://quizlet.com/447810953/exam-2-anatomy-structures-flash-cards/
https://quizlet.com/740016986/anatomy-exam-2-self-exam-questions-flash-cards/

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/nhile/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 384, in onCode
    self.createDeck(deck)
  File "/Users/nhile/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 449, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/nhile/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 497, in fileDownloader
    raise e
  File "/Users/nhile/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 486, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/nhile/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 501, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-01-15T12:55, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, thanks for the detailed description. We already have this issue https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/204. I'm going to close this one in favor of the older issue

I need time to fix this, and I am 99% sure that I will do this over the weekend.
