### ISSUE TITLE
"Quizlet to Anki 2.1 Importer with audio support" Not Working

### ISSUE THREAD

**Issue by nymjk15** [sviatoslav-lebediev/anki-quizlet-importer-extended#208]
**Describe the bug**
When trying to import Quizlet decks I get the following error message:

"Anki encountered a problem. Please follow the troubleshooting steps. Add-ons possibly involved: Quizlet to Anki 21 Importer with audio support".

Anki Deck URL: https://quizlet.com/ma/952762118/fikr-casa-moutanabi-flash-cards/?i=3vmxlq&x=1qqt

Debug info: 

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\nymjk\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 384, in onCode
    ("Importing deck {0}...".format(deck["title"])))
  File "C:\Users\nymjk\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 437, in createDeck
    if item.get('termAudio') and downloadAudio:
  File "C:\Users\nymjk\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 497, in fileDownloader
    debug(f"throwing exception {e.code}")
  File "C:\Users\nymjk\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 486, in fileDownloader
    try:
  File "C:\Users\nymjk\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 501, in download_media
    def download_media (url, file_name, headers):
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-10-10T14:19, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Quizlet deck URL**

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, try to check `Skip errors` checkbox, it's possible that some audio can't be downloaded 
more info here https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ

p.s. here is your deck
[Fikr - CASA Moutanabi.apkg.zip](https://github.com/user-attachments/files/17369126/Fikr.-.CASA.Moutanabi.apkg.zip)
