### ISSUE TITLE
Issue with "image"

### ISSUE THREAD

**Issue by OffCasual** [sviatoslav-lebediev/anki-quizlet-importer-extended#212]
**Describe the bug**
at lines 385 and 452, the add-on is attempting to add an image to a note's field called 'Image'. 

**Quizlet deck URL**
https://quizlet.com/se/842157089/kognitiv-neurovetenskap-flash-cards/

**Comment by sviatoslav-lebediev** [comment]
Hi, https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
4th item. Have you edited a Basic Quizlet Extended note type ?

**Comment by Ducanh777** [comment]
hi i have problem with importing image from quizlet and if i import flashcard with image it will show like this. can you help me?
![image](https://github.com/user-attachments/assets/3ba30279-42f9-4970-b252-51b5e3c608b3)

**Comment by sviatoslav-lebediev** [comment]
Hi could you please click on `Copy Debug Info` and send that text to me ?

**Comment by sviatoslav-lebediev** [comment]
@Ducanh777 i've tried to import your deck and haven't seen any issues, could you try one more time and send me the debug info
p.s. here is your deck
[Unit 18 JR 05_11_2024.apkg.zip](https://github.com/user-attachments/files/17715859/Unit.18.JR.05_11_2024.apkg.zip)

**Comment by Ducanh777** [comment]
debug info:
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "urllib.request", line 1346, in do_open
  File "http.client", line 1285, in request
  File "http.client", line 1331, in _send_request
  File "http.client", line 1280, in endheaders
  File "http.client", line 1040, in _send_output
  File "http.client", line 980, in send
  File "http.client", line 1454, in connect
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1074, in _create
  File "ssl", line 1343, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\phamn\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 385, in onCode
    self.createDeck(deck)
  File "C:\Users\phamn\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 450, in createDeck
    file_name = self.fileDownloader(item["imageUrl"], fallback=True)
  File "C:\Users\phamn\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 487, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "C:\Users\phamn\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 502, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 517, in open
  File "urllib.request", line 534, in _open
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 1389, in https_open
  File "urllib.request", line 1349, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-10-11T01:19, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
@Ducanh777 ok i see that this is a certificate issue, could you try to do this

Open a file from the screenshots and replace the data in that file using this https://raw.githubusercontent.com/sviatoslav-lebediev/anki-quizlet-importer-extended/refs/heads/fix/disable_ssl/__init__.py

I'm going to deploy a fix, but need time to test my changes

![image](https://github.com/user-attachments/assets/a7b438ca-2c80-49eb-9c55-d33b23bb8711)
![image](https://github.com/user-attachments/assets/75db2ec0-4337-47f3-928b-dcb0ea54437f)

**Comment by Ducanh777** [comment]
Thanks, I edited and imported it.

**Comment by sviatoslav-lebediev** [comment]
i've deployed fixed version
