### ISSUE TITLE
Long list of cards with images, exhausted other options to debug, nothing worked. Its the 1st time I encountered issue

### ISSUE THREAD

**Issue by coolbeanz10101010** [sviatoslav-lebediev/anki-quizlet-importer-extended#214]
It hits flashcard #146 and then suddenly pauses / anki freezes
A description of what the bug is.

[**Quizlet deck URL**](https://quizlet.com/409805624/ck-nbmes-flash-cards/)

**Additional context**
Error from the addon window
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 385, in onCode
    self.createDeck(deck)
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 450, in createDeck
    file_name = self.fileDownloader(item["imageUrl"], fallback=True)
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 498, in fileDownloader
    raise e
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 487, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 502, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T09:24, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T09:34, 'None', '']
Auto-refresh browser ['746398558', 2024-10-01T07:50, 'None', '']
Batch Editing ['291119185', 2023-10-25T19:38, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T10:06, 'None', '']
Deadline2 ['723639202', 2024-02-25T21:38, 'None', mod]
Edit Field During Review ['1020366288', 2022-08-29T14:38, 'None', '']
Editor Live Preview ['1960039667', 2024-03-04T17:59, 'None', '']
Export Deck to HTML and Print to PDF ['266464821', 2022-05-25T00:23, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-10-09T21:36, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T14:17, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
Merge Duplicate Notes ['55394168', 2024-01-19T09:16, 'None', '']
Multi search using a list of words ['831327139', 2024-09-12T07:03, 'None', '']
Multiple Choice Note Type ['1859136708', 2024-09-11T16:11, 'None', '']
No Distractions Full Screen Fixed by Shige ['1370336700', 2024-08-26T00:08, 'None', mod]
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-10-10T13:19, 'None', '']
Remove Cloze Button and Hotkey ['1966460736', 2022-05-21T05:29, 'None', mod]
Scale Images ['1312865748', 2023-11-02T01:45, 'None', '']
Special Fields ['1102281552', 2024-10-26T10:51, 'None', '']
Symbols As You Type ['2040501954', 2024-01-19T23:42, 'None', '']

===IDs of active AnkiWeb add-ons===
1020366288 1102281552 1312865748 1362209126 1370336700 1374772155 1859136708 1960039667 1966460736 2040501954 225180905 266464821 291119185 55394168 594329229 723639202 746398558 759844606 831327139 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Customize Keyboard Shortcuts ['24411424', 2023-11-01T04:17, 'None', mod]
FULLER SCREEN hide top toolbar in reviewer ['742922254', 2019-04-04T02:37, 'None', '']
FULLEST SCREEN hide all toolbars in reviewer ['1999609504', 2020-06-09T15:31, 'None', '']
Improved Quizlet to Anki Importer  Ported to 21 ['2072555052', 2018-02-09T08:05, 'None', '']
Opening the same window multiple time ['354407385', 2023-11-04T20:59, 'None', '']
Study-Review Deck ['1026503859', 2024-07-16T06:08, '0.2.1', mod]

**Comment by coolbeanz10101010** [comment]
And again with another deck

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 385, in onCode
    self.createDeck(deck)
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 450, in createDeck
    file_name = self.fileDownloader(item["imageUrl"], fallback=True)
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 498, in fileDownloader
    raise e
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 487, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/parnia/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 502, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T09:24, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T09:34, 'None', '']
Auto-refresh browser ['746398558', 2024-10-01T07:50, 'None', '']
Batch Editing ['291119185', 2023-10-25T19:38, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T10:06, 'None', '']
Deadline2 ['723639202', 2024-02-25T21:38, 'None', mod]
Edit Field During Review ['1020366288', 2022-08-29T14:38, 'None', '']
Editor Live Preview ['1960039667', 2024-03-04T17:59, 'None', '']
Export Deck to HTML and Print to PDF ['266464821', 2022-05-25T00:23, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-10-09T21:36, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T14:17, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
Merge Duplicate Notes ['55394168', 2024-01-19T09:16, 'None', '']
Multi search using a list of words ['831327139', 2024-09-12T07:03, 'None', '']
Multiple Choice Note Type ['1859136708', 2024-09-11T16:11, 'None', '']
No Distractions Full Screen Fixed by Shige ['1370336700', 2024-08-26T00:08, 'None', mod]
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-10-10T13:19, 'None', '']
Remove Cloze Button and Hotkey ['1966460736', 2022-05-21T05:29, 'None', mod]
Scale Images ['1312865748', 2023-11-02T01:45, 'None', '']
Special Fields ['1102281552', 2024-10-26T10:51, 'None', '']
Symbols As You Type ['2040501954', 2024-01-19T23:42, 'None', '']

===IDs of active AnkiWeb add-ons===
1020366288 1102281552 1312865748 1362209126 1370336700 1374772155 1859136708 1960039667 1966460736 2040501954 225180905 266464821 291119185 55394168 594329229 723639202 746398558 759844606 831327139 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Customize Keyboard Shortcuts ['24411424', 2023-11-01T04:17, 'None', mod]
FULLER SCREEN hide top toolbar in reviewer ['742922254', 2019-04-04T02:37, 'None', '']
FULLEST SCREEN hide all toolbars in reviewer ['1999609504', 2020-06-09T15:31, 'None', '']
Improved Quizlet to Anki Importer  Ported to 21 ['2072555052', 2018-02-09T08:05, 'None', '']
Opening the same window multiple time ['354407385', 2023-11-04T20:59, 'None', '']
Study-Review Deck ['1026503859', 2024-07-16T06:08, '0.2.1', mod]

**Comment by coolbeanz10101010** [comment]
Sorry, forgot to click ignore error. Can you please delete this issue on Githib all together? I would really appreciate it.
