### ISSUE TITLE
issue downloading a Quizlet onto Anki

### ISSUE THREAD

**Issue by 1t1na1** [sviatoslav-lebediev/anki-quizlet-importer-extended#218]
hello I was trying to download a Quizlet deck onto anki.

it shows it's private deck so I got the page source and pasted into the tool and also have unticked the audio box and ticked the 'skip error' just in case it fails to work. however it still said 'throwing exception 403' despite I did all this. Debug info below:

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-13.6.9-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 393, in onCode
    self.createDeck(deck)
  File "/Users/.../Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 458, in createDeck
    file_name = self.fileDownloader(item["imageUrl"], fallback=True)
  File "/Users/.../Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 506, in fileDownloader
    raise e
  File "/Users/.../Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 495, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/.../Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 510, in download_media
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Killstreaks - Reward Medals for Correct Answers Fixed by Shige ['1562475180', 2024-09-19T19:43, 'None', mod]
Button Colours Good Again ['2494384865', 2022-09-27T11:18, 'None', '']
Deck name in title 21 ['699175524', 2019-06-01T02:05, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T08:15, 'None', '']
Multiple Choice for Anki ['1566095810', 2023-11-17T20:59, 'None', '']
Progress bar - Visualize reviewed cards and remaining Fixed by Shige ['1708250053', 2024-11-10T20:00, 'None', mod]
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-11-15T09:33, 'None', '']
Remove Duplicate Cards ['95590040', 2024-09-29T16:56, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
See Previous Card Ratings in Reviewer ['1906641654', 2021-08-19T22:32, 'None', '']
Write on your screen ['567651868', 2024-02-04T07:24, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1374772155 1562475180 1566095810 1708250053 1771074083 1906641654 2494384865 567651868 699175524 95590040

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Habitica for 21 ['1758045507', 2024-09-03T11:47, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T11:24, 'None', '']

**Comment by sviatoslav-lebediev** [comment]
Hi, I've tried with these settings and successfully imported your deck, maybe you have selected the `Add reverse` checkbox ?
![image](https://github.com/user-attachments/assets/99ba0e18-1ad0-44ff-bf38-0d451c2f8433)
Here is your deck 
[Topic 13 - Energetics II.apkg.zip](https://github.com/user-attachments/files/17944961/Topic.13.-.Energetics.II.apkg.zip)
