### ISSUE TITLE
Issue Converting 

### ISSUE THREAD

**Issue by nallison906** [sviatoslav-lebediev/anki-quizlet-importer-extended#219]
Keep getting an error when converting any quizlet to Anki. Never had this issue before and it randomly started today

(https://quizlet.com/968851200/oral-path-17-oral-manifestations-systemic-diseases-flash-cards/?i=yxpfa&x=1jqt)

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.1.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/nicolasallison/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 393, in onCode
    self.createDeck(deck)
  File "/Users/nicolasallison/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 458, in createDeck
    file_name = self.fileDownloader(item["imageUrl"], fallback=True)
  File "/Users/nicolasallison/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 495, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/nicolasallison/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 514, in download_media
    f.write(r.read())
  File "http.client", line 476, in read
  File "http.client", line 628, in _safe_read
http.client.IncompleteRead: IncompleteRead(147264 bytes read, 72896 more expected)

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T14:00, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-11-15T04:33, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1374772155 1771074083 295889520

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
it can't download some images - `file_name = self.fileDownloader(item["imageUrl"], fallback=True)`
try to check the `Skip errors` checkbox

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please try one more time? I hope I've fixed the issue
