### ISSUE TITLE
Issue converting

### ISSUE THREAD

**Issue by ghorb2002** [sviatoslav-lebediev/anki-quizlet-importer-extended#220]
I've tried uploading this Quizlet set multiple times, both with and without skipping errors. I've been using this add-on for six months without any issues. I successfully uploaded a set just before this one, but I think the problem might be due to the large number of images in this flashcard set.

https://quizlet.com/979592832/pathology-of-leukemia-lymphoma-and-multiple-myeloma-flash-cards/?new

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/nikkighorbani/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 393, in onCode
    self.createDeck(deck)
  File "/Users/nikkighorbani/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 458, in createDeck
    file_name = self.fileDownloader(item["imageUrl"], fallback=True)
  File "/Users/nikkighorbani/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 495, in fileDownloader
    return download_media(url, file_name, request_headers)
  File "/Users/nikkighorbani/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 514, in download_media
    f.write(r.read())
  File "http.client", line 476, in read
  File "http.client", line 628, in _safe_read
http.client.IncompleteRead: IncompleteRead(147264 bytes read, 79888 more expected)

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-11-15T04:33, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126 1374772155

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by sviatoslav-lebediev** [comment]
Hi, could you please try one more time? I hope I've fixed the issue

**Comment by ghorb2002** [comment]
> Hi, could you please try one more time? I hope I've fixed the issue

It worked, thank you so much!!
