### ISSUE TITLE
Not Working Anymore

### ISSUE THREAD

**Issue by sesomeone1** [sviatoslav-lebediev/anki-quizlet-importer-extended#223]
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-12.7.6-x86_64-i386-64bit

Traceback (most recent call last):
  File "anki.notes", line 162, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 393, in onCode
    self.createDeck(deck)
  File "/Users/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 440, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 170, in __setitem__
  File "anki.notes", line 164, in _field_index
KeyError: 'FrontText'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-11-15T04:33, 'None', '']

===IDs of active AnkiWeb add-ons===
1362209126

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Quizlet deck URL**
https://quizlet.com/983386994/dental-anatomy-final-exam-flash-cards/?i=axjou&x=1jqt

**Comment by sviatoslav-lebediev** [comment]
Hi, please take a look at https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ
4th item
