### ISSUE TITLE
KeyError: 'FrontAudio'

### ISSUE THREAD

**Issue by ThePieMonster** [sviatoslav-lebediev/anki-quizlet-importer-extended#24]
Looks like some error handling is needed here:

```
Anki 2.1.39 (576f0043) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-04-24 14:09:57

Caught exception:
Traceback (most recent call last):
  File "anki\notes.py", line 106, in _fieldOrd
KeyError: 'FrontAudio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 302, in onCode
    self.createDeck(deck)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 354, in createDeck
    note["FrontAudio"] = "[sound:" + file_name + "]"
  File "anki\notes.py", line 114, in __setitem__
  File "anki\notes.py", line 108, in _fieldOrd
KeyError: 'FrontAudio'

```

**Comment by sviatoslav-lebediev** [comment]
Hi, have you changed a deck that this plugin uses?

**Comment by sviatoslav-lebediev** [comment]
https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/issues/25
