### ISSUE TITLE
'FrontText' Error

### ISSUE THREAD

**Issue by FutureDogtor** [sviatoslav-lebediev/anki-quizlet-importer-extended#70]
**Describe the bug**
I was having no issues with this plug in for a while- thank you for all your work you put into making it! However I've been having issues where I can no longer convert any quizlets due to a consistent error evidenced below. The term 'FrontText' looks like its coming up in the error debug message but I'm not sure how to fix that.

**Quizlet deck URL**
https://quizlet.com/793361863/immuno-quiz-5-flash-cards/?funnelUUID=d5f6b6c8-2dd2-42e2-a525-eea9497c3671

**Additional context**
Error from the addon window
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-04-19 14:42:43

Caught exception:
Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'FrontText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ally Eaton\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 294, in onCode
    self.createDeck(deck)
  File "C:\Users\Ally Eaton\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 341, in createDeck
    note["FrontText"] = item["term"]
  File "anki.notes", line 162, in __setitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'FrontText'

**Comment by FutureDogtor** [comment]
I think I fixed it or at least made a sustainable work around now so we're good now!
