### ISSUE TITLE
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5 Platform: Windows 10 Flags: frz=True ao=True sv=2 Add-ons, last update check: 2023-05-15 19:05:51  Caught exception: Traceback (most recent call last):   File "anki.notes", line 154, in _field_index KeyError: 'FrontText'  The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "C:\Users\User\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 294, in onCode     self.createDeck(deck)   File "C:\Users\User\AppData\Roaming\Anki2\addons21\1362209126\__init__.py", line 341, in createDeck     note["FrontText"] = item["term"]   File "anki.notes", line 162, in __setitem__   File "anki.notes", line 156, in _field_index KeyError: 'FrontText'

### ISSUE THREAD

**Issue by Tutri** [sviatoslav-lebediev/anki-quizlet-importer-extended#75]
**Describe the bug**
A description of what the bug is.

**Quizlet deck URL**

**Additional context**
Error from the addon window

**Comment by sviatoslav-lebediev** [comment]
Hi, could you try to remove `Basic Quizlet Extended` note type ? Maybe you have changed it somehow, it's a "system" note type, so I would not recommend changing it.

**Comment by sviatoslav-lebediev** [comment]
I will close this ticket, re-open it, or create a new one if you still can't import decks.
