### ISSUE TITLE
Quizlet importer still not working after 6/18/23 update :(

### ISSUE THREAD

**Issue by jessm-ess** [sviatoslav-lebediev/anki-quizlet-importer-extended#98]
Hello,

I tried importing a quizlet deck after the update and it seemed to work at first. However, after downloading the first 9 cards, an error occurs. 

See below:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-06-18 13:23:16
Add-ons possibly involved: ⁨Quizlet to Anki 21 Importer with audio support⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/jessienickolas/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 373, in onCode
    self.createDeck(deck)
  File "/Users/jessienickolas/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 438, in createDeck
    file_name = self.fileDownloader(item["imageUrl"])
  File "/Users/jessienickolas/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 480, in fileDownloader
    raise e
  File "/Users/jessienickolas/Library/Application Support/Anki2/addons21/1362209126/__init__.py", line 471, in fileDownloader
    r = urllib2.urlopen(urllib2.Request(url, headers=headers))
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

Quizlet URL: https://quizlet.com/810470703/introduction-to-clinically-oriented-anatomy-flash-cards/?funnelUUID=5c65f270-56db-46df-9d9b-fbd1daff74c9

Please assist and thank you for all that you do!

**Comment by sviatoslav-lebediev** [comment]
```
File "/Users/jessienickolas/Library/Application Support/Anki2/addons21/1362209126/init.py", line 438, in createDeck
file_name = self.fileDownloader(item["imageUrl"])
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

This means that for some reason quizlet doesn't allow downloading some images. I would recommend checking `Skip errors` checkbox and after the import check the imported images, some of them will be absent (you can add them manually).

**Comment by jessm-ess** [comment]
Okay, I will try this!

Thank you!

**Comment by sviatoslav-lebediev** [comment]
I'm going to close this issue, create a new one if you still can't import

**Comment by jessm-ess** [comment]
It worked!

Thank you,

Jess
